name: lmke-warps
version: '${project.version}'
main: dev.lmke.mc.warps.LMKEWarps
api-version: 1.15
description: Highly customizable warp plugin with economy support and map integrations
website: lmke.dev
commands:
  warp:
    usage: "/warp <create|delete|help|<name>> [name]"
    description: Warp command
  poi:
    usage: "/poi <create|delete|help|<name>> [name]"
    description: Point of interest command

softdepend:
  - BlueMap
  - Vault
  - dynmap